quarkus:
  datasource:
    username:
    password:

    db-kind: postgresql
    jdbc:
      url:

  hibernate-orm:
    sql-load-script:
    database:
      default-schema: trainer_app
      schema-management:
        strategy: none
    log:
      sql: false