quarkus:
  http:
    root-path: /api
  datasource:
    username: quarkus
    password: quarkus

    db-kind: postgresql

  hibernate-orm:
    sql-load-script:
    database:
      default-schema: public
      schema-management:
        strategy: none
      generation: update
    log:
      sql: true
      format-sql: true
  liquibase:
    default-schema-name: public
    migrate-at-start: true
    change-log: db/changelog/db.changelog-master.xml

  smallrye-openapi:
    auto-add-security: false

smallrye:
  jwt:
    sign:
      key:
        location: privateKey.pem
    encrypt:
      key:
        location: publicKey.pem
    verify:
      key:
        location: publicKey.pem
mp:
  jwt:
    verify:
      key:
        location: publicKey.pem
      issuer: trainer-app
